apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cook-we-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/quent36987/cook-we-config.git'
    targetRevision: HEAD
    path: .
    plugin:
      name: argocd-vault-plugin
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
