apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cook-we-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/quent36987/cook-we-config.git'
    targetRevision: HEAD
    path: .
    helm:
      parameters:
        - name: secret.port
          valueFrom:
            secretKeyRef:
              name: cook-we-back-secrets
              key: PORT
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
