apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: your-github-registry-url/front:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  namespace: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back
          image: your-github-registry-url/back:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db-service.db:5432/yourdbname
            - name: SPRING_DATASOURCE_USERNAME
              value: yourusername
            - name: SPRING_DATASOURCE_PASSWORD
              value: yourpassword
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: yourdbname
            - name: POSTGRES_USER
              value: yourusername
            - name: POSTGRES_PASSWORD
              value: yourpassword

