apiVersion: apps/v1
kind: Deployment
metadata:
  name: cook-we-front-deployment
  namespace: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cook-we-front
  template:
    metadata:
      labels:
        app: cook-we-front
    spec:
      containers:
        - name: front
          image: ghcr.io/quent36987/cook-we-app:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cook-we-back-deployment
  namespace: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cook-we-back
  template:
    metadata:
      labels:
        app: cook-we-back
    spec:
      containers:
        - name: cook-we-back
          image: ghcr.io/quent36987/cook-we:latest
          ports:
            - containerPort: 9001
          env:
            - name: PORT
              value: "9001"
            - name: BD_URL
              value: jdbc:postgresql://postgres-service.db:5432/cook-we-bdd
            - name: BD_USER
              value: admin
            - name: BD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-back
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-back
                  key: JWT_SECRET
            - name: JWT_EXPIRATION_MS
              value: "86400000"
            - name: JWT_COOKIE_NAME
              value: bezkoder-jwt
            - name: PICTURE_PATH
              value: /var/lib/uploads
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: secret-back
                  key: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: secret-back
                    key: ADMIN_PASSWORD
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-back
                  key: ADMIN_USERNAME
          volumeMounts:
            - mountPath: /var/lib/uploads
              name: upload-volume
      volumes:
        - name: upload-volume
          persistentVolumeClaim:
            claimName: upload-pvc
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-back
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: cook-we-bdd
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---



