apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: back
spec:
  rules:
    - host: "*"
      http:
        paths:
          - path: /back
            pathType: Prefix
            backend:
              service:
                name: cook-we-back-service
                port:
                  number: 9001
          - path: /front
            pathType: Prefix
            backend:
              service:
                name: cook-we-front-service
                port:
                  number: 80

