apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  plugin: |
    - name: argocd-vault-plugin
      version: v1.18.1
      path: /usr/local/bin/argocd-vault-plugin
      repository: https://github.com/argoproj-labs/argocd-vault-plugin
      configuration: |
        secrets:
          - name: sops-key
            type: generic
            key: age.key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-server
    spec:
      containers:
        - name: argocd-server
          image: argoproj/argocd:latest
        - name: argocd-vault-plugin
          image: argoproj-labs/argocd-vault-plugin:1.18.1
          command: ["/usr/local/bin/argocd-vault-plugin"]