apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: database
    namespace: default
spec:
    encryptedData:
        PORT: AgB/lNU40k5Avu+SlK0kdQb03zExye1t5LNqosAzpAUgFwqBCQ/ynT2PHiL+VAAGn3Ca0YZj8gq0VsqYMYMqpNPPrrKa6ovcN4Iu8vpXQVW3aCuP0DdStNTD8JQ7Q3CDFeq0A9AEtbjC6tW6brxJ7GwHXk2ADB46EVdNTSMm7hFlg8r8mc+sKFDMePpQNxRNQxXedRmhO3DDzdAddFe6iWtkxD5HH80iocdxkzlNGgA0nRJcmeJ4f80ZR0QcjzRwzYzdgrkUkltGbzzOS88fXyZK33J1/yuVvCnUSMvbOM9QJZt6nZCHszw4OlEiTvgQRbLnc+9rKvlSa2cjQz16VAu9CaYBT3UxO0jhmBIs6+x6tG97sISZtaaNBg9j6VZg9Egc1qeJfCTEkOfz4PteoAvv2hGgU2zE1iu//ks5dJXEWKOsTVF4RCaDzUPyVgKt0pReiEB0yU8v6DcXfYGQw/hacGUhkv62ai5IAOfjG5BjQDOeWcjIs++hHw4pfuX/v1OZqDPJt2yEjijEV6t6IE0pmwivB5d01ULP2IpyGvwYHlEd6vuUeAsVjZJaLr7vgsD9nBK2/FAx0/QRhPMml2GJ/Bn7gxdyg/vehel0u3UnvxLBUvTK0KSxyBSHIk63JKNg7wkb6n9ForZXQzLT9AwqbzmaKC3SObBR6585bD+UMpH3v2S4I7fp8CU1NdToahkEZ94L