apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: front
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: cook-we-back-service
  namespace: back
spec:
  selector:
    app: cook-we-back
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: db
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
